from typing import Protocol, Dict, Any, List
from .models import Message

class Repo(Protocol):
    async def get_or_create_session(self, session_id: str, user_id: str) -> Dict[str, Any]: ...
    async def append_message(self, session_id: str, user_id: str, msg: Message) -> Dict[str, Any]: ...
    async def replace_recent_messages(self, session_id: str, new_tail: List[Dict[str, Any]], new_summary: Dict[str, Any], unlock: bool = True) -> None: ...
    async def try_lock_summarize(self, session_id: str) -> bool: ...
    async def unlock_summarize(self, session_id: str) -> None: ...
    async def update_state(self, session_id: str, flat_patch: Dict[str, Any]) -> None: ...
    async def upsert_user_profile(self, user_id: str, patch: Dict[str, Any]) -> Dict[str, Any]: ...
    async def upsert_user_memories_bulk(self, user_id: str, items: List[Dict[str, Any]]) -> Dict[str, Any]: ...
